language: python

matrix:
  include:

python:
  - "3.6"
 # Install dependencies
before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - ls /home/travis
  - conda update --yes conda
# The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
#  - sudo rm -rf /dev/shm
#  - sudo ln -s /run/shm /dev/shm
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install -y -c flyem-forge neuprint-python
  - pip install -r paths_to_targets/requirements.txt
script:
  - pylint --disable=C,W,R paths_to_targets/*.py